### ISSUE TITLE
mx-dropdown 'save changes'

### ISSUE THREAD

**Issue by nofoto** [reduzent/netpd-instruments#45]
Pd asks if the user wants to save changes to 'mx-dropdown' when trying to quit at the end of a session - as this is for each instance of the patch it can produce a lot of messages. Workaround is to click 'unpatch' at the end of a session but this won't be obvious to many users.

**Comment by reduzent** [comment]
It's a regression introduced in Pd 0.52. It is fixed in Pd 0.52-2 (the most recent release as of now).

Check here: https://github.com/pure-data/pure-data/issues/1511

mx-dropdown supports setting the font size dynamically, which marks the abstraction dirty in the affected versions of Pd. As you pointed out, you can avoid the dialogs either by closing unpatch before quitting Pd. Alternatively, you could upgrade to the most recent Pd.

**Comment by reduzent** [comment]
Fix in Pd
